/* AUTO-GENERATED by generate-gallery.js — do not edit manually.
   Run:  node generate-gallery.js
   135 images  |  3 categories
   Generated: 2026-07-02T11:33:24.653Z
*/
window.GALLERY_IMAGES = [
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/combination/1.jpeg",
    "cat": "mfg",
    "label": "Combination Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/combination/2.png",
    "cat": "mfg",
    "label": "Combination Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/combination/3.png",
    "cat": "mfg",
    "label": "Combination Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/combiwasher/1.jpeg",
    "cat": "mfg",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/combiwasher/2.png",
    "cat": "mfg",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/combiwasher/4.png",
    "cat": "mfg",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/csk-head-torx/1.jpeg",
    "cat": "mfg",
    "label": "CSK Torx Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/csk-phillips/1.jpeg",
    "cat": "mfg",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/csk-phillips/2.png",
    "cat": "mfg",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/csk-phillips/3.png",
    "cat": "mfg",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/ln-button-head/2.jpg",
    "cat": "mfg",
    "label": "LN Button Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/ln-button-head/3.png",
    "cat": "mfg",
    "label": "LN Button Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/ln-csk-head/1.jpeg",
    "cat": "mfg",
    "label": "LN CSK Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/pan-head-torx/1.png",
    "cat": "mfg",
    "label": "Pan Head Torx"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/pan-head-torx/2.jpeg",
    "cat": "mfg",
    "label": "Pan Head Torx"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/pan-phillips/1.jpeg",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/pan-phillips/2.png",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/pan-phillips/3.png",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/pan-phillips/4.png",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/torx-button-head/1.png",
    "cat": "mfg",
    "label": "Torx Button Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/torx-button-head/2.jpg",
    "cat": "mfg",
    "label": "Torx Button Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/truss-phillips/1.png",
    "cat": "mfg",
    "label": "Truss Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/truss-phillips/2.png",
    "cat": "mfg",
    "label": "Truss Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/machine-screw/truss-phillips/3.jpg",
    "cat": "mfg",
    "label": "Truss Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/combination/1.jpeg",
    "cat": "mfg",
    "label": "Combination Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/combination/2.png",
    "cat": "mfg",
    "label": "Combination Head"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/combiwasher/1.jpeg",
    "cat": "mfg",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/combiwasher/2.jpg",
    "cat": "mfg",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/csk-phillips/1.jpeg",
    "cat": "mfg",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/csk-phillips/2.jpg",
    "cat": "mfg",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/pan-phillips/1.jpeg",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/pan-phillips/2.jpg",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/pan-phillips/3.jpg",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/pan-phillips/4.jpg",
    "cat": "mfg",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/truss-phillips/1.jpeg",
    "cat": "mfg",
    "label": "Truss Phillips"
  },
  {
    "src": "/assets/gallery/product-images/mfg/self-tapping/wooden-screw/1.jpeg",
    "cat": "mfg",
    "label": "Wooden Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/allen-bolt/button-head-ln-bolt/1.jpg",
    "cat": "trd",
    "label": "Button Head Ln Bolt"
  },
  {
    "src": "/assets/gallery/product-images/trd/allen-bolt/csk-head-ln-bolt/2.jpeg",
    "cat": "trd",
    "label": "CSK LN Bolt"
  },
  {
    "src": "/assets/gallery/product-images/trd/allen-bolt/csk-head-ln-bolt/2.jpg",
    "cat": "trd",
    "label": "CSK LN Bolt"
  },
  {
    "src": "/assets/gallery/product-images/trd/allen-bolt/ln-bolt/1.jpg",
    "cat": "trd",
    "label": "Ln Bolt"
  },
  {
    "src": "/assets/gallery/product-images/trd/allen-bolt/ln-bolt/2.jpg",
    "cat": "trd",
    "label": "Ln Bolt"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/bolt-type-fastner/1.jpg",
    "cat": "trd",
    "label": "Bolt Type Fastener"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/bolt-type-fastner/2.jpg",
    "cat": "trd",
    "label": "Bolt Type Fastener"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/coach-head-screw/1.jpg",
    "cat": "trd",
    "label": "Coach Head Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/coach-head-screw/2.jpg",
    "cat": "trd",
    "label": "Coach Head Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/coach-head-screw/3.jpg",
    "cat": "trd",
    "label": "Coach Head Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/frame-fixing-fastener/1.jpeg",
    "cat": "trd",
    "label": "Frame Fixing"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/frame-fixing-fastener/2.jpeg",
    "cat": "trd",
    "label": "Frame Fixing"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/hook-type-fastener/1.jpeg",
    "cat": "trd",
    "label": "Hook Type Fastener"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/hook-type-fastener/2.jpeg",
    "cat": "trd",
    "label": "Hook Type Fastener"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/hook-type-fastener/3.jpg",
    "cat": "trd",
    "label": "Hook Type Fastener"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/pin-type-fastener/1.jpg",
    "cat": "trd",
    "label": "Pin Type Fastener"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/pin-type-fastener/2.jpg",
    "cat": "trd",
    "label": "Pin Type Fastener"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/wegde-anchor-fastener/1.jpg",
    "cat": "trd",
    "label": "Wedge Anchor"
  },
  {
    "src": "/assets/gallery/product-images/trd/fasteners/wegde-anchor-fastener/3.jpg",
    "cat": "trd",
    "label": "Wedge Anchor"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/combi-washer-machine/1.jpg",
    "cat": "trd",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/combi-washer-machine/2.jpg.png",
    "cat": "trd",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/combi-washer-machine/4.jpg",
    "cat": "trd",
    "label": "Combi Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/csk-phillips/2.jpg",
    "cat": "trd",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/csk-phillips/4.jpg",
    "cat": "trd",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/pan-phillips-washer/2.jpg",
    "cat": "trd",
    "label": "Pan Phillips Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/pan-phillips-washer/4.jpg",
    "cat": "trd",
    "label": "Pan Phillips Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/machine-screw/truss-phillips/1.jpg",
    "cat": "trd",
    "label": "Truss Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/aluminium-pop-rivet/3.jpg",
    "cat": "trd",
    "label": "Aluminium Pop Rivet"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/aluminium-pop-rivet/4.jpg",
    "cat": "trd",
    "label": "Aluminium Pop Rivet"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/coloured-pop-rivet/2.jpg",
    "cat": "trd",
    "label": "Coloured Pop Rivet"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/coloured-pop-rivet/4.jpg",
    "cat": "trd",
    "label": "Coloured Pop Rivet"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/double-hand-riveting-gun/2.jpg",
    "cat": "trd",
    "label": "Double Hand Riveting Gun"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/double-hand-riveting-gun/3.jpg",
    "cat": "trd",
    "label": "Double Hand Riveting Gun"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/hammer-rivet/2.jpg",
    "cat": "trd",
    "label": "Hammer Rivet"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/hammer-rivet/4.jpg",
    "cat": "trd",
    "label": "Hammer Rivet"
  },
  {
    "src": "/assets/gallery/product-images/trd/rivets/tinmen-rivet/2.jpeg",
    "cat": "trd",
    "label": "Tinmen Rivet"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/csk-head-sds/1.jpeg",
    "cat": "trd",
    "label": "CSK Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/csk-head-sds/2.jpg",
    "cat": "trd",
    "label": "CSK Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/csk-head-sds/3.jpg",
    "cat": "trd",
    "label": "CSK Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/csk-head-sds/4.jpg",
    "cat": "trd",
    "label": "CSK Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/cyclone-washers/1.jpeg",
    "cat": "trd",
    "label": "Cyclone Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/cyclone-washers/2.jpeg",
    "cat": "trd",
    "label": "Cyclone Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/cyclone-washers/4.jpg",
    "cat": "trd",
    "label": "Cyclone Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/epdm-bonded-hex-flange/2.jpeg",
    "cat": "trd",
    "label": "EPDM Hex Flange"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/epdm-washer/2.jpg",
    "cat": "trd",
    "label": "EPDM Washer"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/hex-head-sds/1.jpg",
    "cat": "trd",
    "label": "Hex Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/hex-head-sds/2.jpg",
    "cat": "trd",
    "label": "Hex Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/hex-head-sds/3.jpg",
    "cat": "trd",
    "label": "Hex Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/hex-head-sds/5.jpg",
    "cat": "trd",
    "label": "Hex Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/hex-head-sds/finethread1.jpg",
    "cat": "trd",
    "label": "Hex Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/hex-head-stitching/1.jpeg",
    "cat": "trd",
    "label": "Hex Head Stitching"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/pan-head-sds/2.jpg",
    "cat": "trd",
    "label": "Pan Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/pan-head-sds/4.png",
    "cat": "trd",
    "label": "Pan Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/ph2-bitt/1.jpeg",
    "cat": "trd",
    "label": "PH2 Bit"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/ph2-bitt/3.jpg",
    "cat": "trd",
    "label": "PH2 Bit"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/sds-sockett/1.jpeg",
    "cat": "trd",
    "label": "SDS Socket"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/sds-sockett/2.jpeg",
    "cat": "trd",
    "label": "SDS Socket"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/sds-sockett/3.jpeg",
    "cat": "trd",
    "label": "SDS Socket"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/truss-head-sds/2.jpg",
    "cat": "trd",
    "label": "Truss Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-drilling/truss-head-sds/4.jpg",
    "cat": "trd",
    "label": "Truss Head SDS"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/chipboard-screw/2.jpg",
    "cat": "trd",
    "label": "Chipboard Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/chipboard-screw/3.jpg",
    "cat": "trd",
    "label": "Chipboard Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/chipboard-screw/4.jpg",
    "cat": "trd",
    "label": "Chipboard Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/combi-washer-screw/1.jpeg",
    "cat": "trd",
    "label": "Combi Washer Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/combination-head-screw/3.png",
    "cat": "trd",
    "label": "Combination Head"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/csk-phillips-screw/1.jpeg",
    "cat": "trd",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/csk-phillips-screw/2.jpg",
    "cat": "trd",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/csk-phillips-screw/4.jpg",
    "cat": "trd",
    "label": "CSK Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/csk-slotted-screw/1.jpeg",
    "cat": "trd",
    "label": "CSK Slotted"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/csk-slotted-screw/2.jpeg",
    "cat": "trd",
    "label": "CSK Slotted"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/csk-slotted-screw/4.jpg",
    "cat": "trd",
    "label": "CSK Slotted"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/drywall-screw/2.jpg",
    "cat": "trd",
    "label": "Drywall Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/drywall-screw/3.jpeg",
    "cat": "trd",
    "label": "Drywall Screw"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/pan-phillips-screw/1.jpeg",
    "cat": "trd",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/pan-phillips-screw/2.jpeg",
    "cat": "trd",
    "label": "Pan Phillips"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/pan-slotted-screw/1.jpeg",
    "cat": "trd",
    "label": "Pan Slotted"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/truss-head-screw/2.jpg",
    "cat": "trd",
    "label": "Truss Head"
  },
  {
    "src": "/assets/gallery/product-images/trd/self-tapping/truss-head-screw/3.jpg",
    "cat": "trd",
    "label": "Truss Head"
  },
  {
    "src": "/assets/gallery/factory-images/closeup-caliper-measuring-screw.jpg",
    "cat": "factory-images",
    "label": "Closeup Caliper Measuring Screw"
  },
  {
    "src": "/assets/gallery/factory-images/closeup-caliper-screw-diameter.jpg",
    "cat": "factory-images",
    "label": "Closeup Caliper Screw Diameter"
  },
  {
    "src": "/assets/gallery/factory-images/closeup-machine-die-tooling.jpg",
    "cat": "factory-images",
    "label": "Closeup Machine Die Tooling"
  },
  {
    "src": "/assets/gallery/factory-images/closeup-sack-of-stainless-steel-screws.jpg",
    "cat": "factory-images",
    "label": "Closeup Sack Of Stainless Steel Screws"
  },
  {
    "src": "/assets/gallery/factory-images/factory-floor-workers-overview.jpg",
    "cat": "factory-images",
    "label": "Factory Floor Workers Overview"
  },
  {
    "src": "/assets/gallery/factory-images/factory-team-group-photo.jpg",
    "cat": "factory-images",
    "label": "Factory Team Group Photo"
  },
  {
    "src": "/assets/gallery/factory-images/office-desk-laptop-work.jpg",
    "cat": "factory-images",
    "label": "Office Desk Laptop Work"
  },
  {
    "src": "/assets/gallery/factory-images/women-packing-screws-into-boxes.jpg",
    "cat": "factory-images",
    "label": "Women Packing Screws Into Boxes"
  },
  {
    "src": "/assets/gallery/factory-images/women-packing-screws-warehouse.jpg",
    "cat": "factory-images",
    "label": "Women Packing Screws Warehouse"
  },
  {
    "src": "/assets/gallery/factory-images/worker-adjusting-machine-hopper.jpg",
    "cat": "factory-images",
    "label": "Worker Adjusting Machine Hopper"
  },
  {
    "src": "/assets/gallery/factory-images/worker-adjusting-screw-making-machine.jpg",
    "cat": "factory-images",
    "label": "Worker Adjusting Screw Making Machine"
  },
  {
    "src": "/assets/gallery/factory-images/worker-inspecting-machine-mechanism.jpg",
    "cat": "factory-images",
    "label": "Worker Inspecting Machine Mechanism"
  },
  {
    "src": "/assets/gallery/factory-images/worker-loading-screws-polishing-drum.jpg",
    "cat": "factory-images",
    "label": "Worker Loading Screws Polishing Drum"
  },
  {
    "src": "/assets/gallery/factory-images/worker-lubricating-machine.jpg",
    "cat": "factory-images",
    "label": "Worker Lubricating Machine"
  },
  {
    "src": "/assets/gallery/factory-images/worker-measuring-part-with-caliper.jpg",
    "cat": "factory-images",
    "label": "Worker Measuring Part With Caliper"
  },
  {
    "src": "/assets/gallery/factory-images/worker-operating-cold-heading-machine.jpg",
    "cat": "factory-images",
    "label": "Worker Operating Cold Heading Machine"
  },
  {
    "src": "/assets/gallery/factory-images/worker-operating-thread-rolling-machine.jpg",
    "cat": "factory-images",
    "label": "Worker Operating Thread Rolling Machine"
  },
  {
    "src": "/assets/gallery/factory-images/worker-servicing-large-machine.jpg",
    "cat": "factory-images",
    "label": "Worker Servicing Large Machine"
  },
  {
    "src": "/assets/gallery/factory-images/worker-servicing-machine-with-wrench.jpg",
    "cat": "factory-images",
    "label": "Worker Servicing Machine With Wrench"
  },
  {
    "src": "/assets/gallery/factory-images/worker-servicing-nut-former-machine.jpg",
    "cat": "factory-images",
    "label": "Worker Servicing Nut Former Machine"
  },
  {
    "src": "/assets/gallery/factory-images/worker-using-hammer-and-punch.jpg",
    "cat": "factory-images",
    "label": "Worker Using Hammer And Punch"
  }
];
window.GALLERY_CAT_LABELS = {
  "mfg": "Manufacturing",
  "trd": "Trading",
  "factory-images": "Factory Images"
};
